import type { ChatDisplayMessage } from "@/components/chat/ChatMessageList";
import type { ThinkingMapData } from "@/server/ai/analysis";

export function exportSessionAsMarkdown(
  title: string,
  topic: string,
  messages: ChatDisplayMessage[],
  thinkingMap?: ThinkingMapData | null,
) {
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let content = `# 📘 Study Notes: ${title}\n\n`;
  content += `**Topic:** ${topic}  \n`;
  content += `**Date:** ${dateStr}  \n`;
  content += `**Generated by:** [SocraticAI](https://socratic-ai-tau.vercel.app/)\n\n`;

  content += `---\n\n## 💬 Socratic Study Dialogue\n\n`;

  messages.forEach((msg, idx) => {
    if (!msg.content) return;
    const speaker = msg.role === "USER" ? "👤 **Student**" : "🎓 **Socratic Tutor**";
    content += `### ${speaker} (Step ${idx + 1})\n\n${msg.content}\n\n`;
  });

  if (thinkingMap) {
    content += `---\n\n## 📊 Learning Breakdown & Summary\n\n`;
    content += `### 💡 Key Insight\n> ${thinkingMap.keyInsight}\n\n`;
    content += `### 📝 Session Summary\n${thinkingMap.summary}\n\n`;

    if (thinkingMap.misconceptions && thinkingMap.misconceptions.length > 0) {
      content += `### 🎯 Targeted Misconceptions\n`;
      thinkingMap.misconceptions.forEach((item) => {
        content += `- ${item}\n`;
      });
      content += `\n`;
    }
  }

  const blob = new Blob([content], { type: "text/markdown;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  const fileName = `${title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-study-notes.md`;
  link.setAttribute("download", fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportSessionAsPrintablePDF() {
  if (typeof window !== "undefined") {
    window.print();
  }
}
